trigger:
- master

variables:
  CODE_SIGN_ID: 'Developer ID Installer: The University of Tromso (2K5J2584NX)'

jobs:
- job: 'macOS'
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      addToPath: true
  - script: |
      curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
      git clone --branch feature/new-format https://github.com/divvun/kbdgen.git
      git clone https://github.com/divvun/divvun-ci-config.git
      cd divvun-ci-config
      sh ./install-macos.sh
    displayName: 'Install prerequisites'
    env:
      DIVVUN_KEY: $(divvunKey)
  - script: |
      python -m venv $HOME/env/py3
      source $HOME/env/py3/bin/activate
      source $HOME/.poetry/env
      cd kbdgen
      poetry install
      cd ../crk.kbdgen
      kbdgen -R -t=mac .
    displayName: 'Run kbdgen'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/crk.kbdgen/Plains Cree Keyboards 0.1.0.pkg'
      artifactName: macos
- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      addToPath: true
  - bash: |
      curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
      git clone --branch feature/new-format https://github.com/divvun/kbdgen.git || exit 1
      git clone https://github.com/divvun/divvun-ci-config.git || exit 1
      openssl aes-256-cbc -d -in ./divvun-ci-config/config.txz.enc -pass pass:$DIVVUN_KEY -out config.txz -md md5 || exit 1
      7z e config.txz || exit 1
      tar xf config.tar || exit 1
      curl -o 6aa798a39c.zip https://x.brendan.so/6aa798a39c.zip || exit 1
      7z x 6aa798a39c.zip || exit 1
    displayName: 'Install prerequisites'
    env:
      DIVVUN_KEY: $(divvunKey)
  - powershell: |
      $Env:PATH += $Env:USERPROFILE + "\.poetry\bin;"
      $Env:CODESIGN_PFX = "$(System.DefaultWorkingDirectory)\enc\creds\windows\divvun.pfx"
      $Env:MSKLC_PATH = "$(System.DefaultWorkingDirectory)\msklc1.4"
      $env:VIRTUAL_ENV_DISABLE_PROMPT="true"
      python -m venv $Env:USERPROFILE\env\py3
      Invoke-Expression -Command $Env:USERPROFILE\env\py3\Scripts\Activate.ps1
      cd kbdgen
      poetry install
      kbdgen -R -t win ..\crk.kbdgen --logging trace
    displayName: 'Run kbdgen'
    env:
      CODESIGN_PW: $(pfxPassword)
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/kbdgen/Plains_Cree_Keyboards_0.1.2.exe'
      artifactName: windows
- job: 'Android'
  pool:
    vmImage: 'ubuntu-16.04'
  container: bitbleep/kbdgen-android:0.1
  steps:
  - script: |
      curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python3
      curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
      source $HOME/.cargo/env
      rustup target add aarch64-linux-android
      rustup target add armv7-linux-androideabi
      rustup target add i686-linux-android
      cargo install cargo-ndk
      git clone --branch feature/new-format https://github.com/divvun/kbdgen.git
      git clone https://github.com/divvun/divvun-ci-config.git
      cd divvun-ci-config
      openssl aes-256-cbc -d -in config.txz.enc -pass pass:$DIVVUN_KEY -md md5 | tar xfJ -
      cp -R enc/creds $HOME
    displayName: 'Install prerequisites'
    env:
      DIVVUN_KEY: $(divvunKey)
  - script: |
      source $HOME/.cargo/env
      source $HOME/.poetry/env
      python3 -m venv $HOME/env/py3
      source $HOME/env/py3/bin/activate
      source divvun-ci-config/enc/env.sh
      cd kbdgen
      poetry install
      cd ../crk.kbdgen
      kbdgen -R -t android -o output --github-username $GITHUB_USERNAME --github-token $GITHUB_TOKEN --logging=debug .
      ls output
    displayName: 'Run kbdgen'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/crk.kbdgen/output/.-0.1.0_release.apk'
      artifactName: android
