trigger:
- master

variables:
  CODE_SIGN_ID: 'Developer ID Installer: The University of Tromso (2K5J2584NX)'

- job: 'macOS'
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      addToPath: true
  - script: |
      curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
      git clone --branch feature/new-format https://github.com/divvun/kbdgen.git
      git clone https://github.com/divvun/divvun-ci-config.git
      cd divvun-ci-config
      sh ./install-macos.sh
    displayName: 'Install prerequisites'
    env:
      DIVVUN_KEY: $(divvunKey)
  - script: |
      python -m venv $HOME/env/py3
      source $HOME/env/py3/bin/activate
      source $HOME/.poetry/env
      cd kbdgen
      poetry install
      cd ../crk.kbdgen
      kbdgen -R -t=mac .
    displayName: 'Run kbdgen'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/crk.kbdgen/Plains Cree Keyboards 0.1.0.pkg'
      artifactName: crk-keyboard-macos.pkg
