internalName: crk

locales:
  en:
    name: &bundleName "Plains Cree Keyboards"
    description: "Mobile OS keyboards for  languages from the Divvun group at UiT."
  crk:
    name: "nēhiyawēwin"
    description: "Mobiltastatur for Plains Cree fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga árktalaš universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga árktalaš universitehta

layouts: [crk-mobile, crk-mac, crk-win]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.crk
    icon: images/plainwheel.jpg
    keyStore: $GTPRIV/admin/dev-accounts/dev_keys/sami_keyboard.keystore
    keyAlias: sami_keyboard

  ios: &AppleID
    codeSignId: "Developer ID Installer: The University of Tromso (2K5J2584NX)"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.crk
    bundleName: *bundleName
    icon: images/crk-icon.png

  osx:
    <<: *AppleID
    icon: images/crk-keyboard-menu-icon.png
    version: 0.1.0
    resources: doc

  win:
    appName: *bundleName
    version: 0.1.0
    url: "http://divvun.no"
    uuid: "30FECDF9-1785-475E-85E6-61D2822F4340"
