locales:
  en:
    name: Plains Cree Keyboards
    description: Mobile OS keyboards for languages from the Divvun group at UiT.
  crk:
    name: nēhiyawēwin
    description: Mobiltastatur for Plains Cree fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga árktalaš universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga árktalaš universitehta
